---
title: "Compensation "
output: github_document
---

## Project Overview

The question I have revolves around worker compensation. 
Given a variety of factors such as
experience, 
age,
industry,
gender,
locale,
part-time status,
and worker preferences,
how much should an employee be paid?
If an employee is more productive and beneficial to a given firm,
is it true that they are compensated more?

In this brief project, I will attempt to explore the differences between compensation
for employees based on a variety of factors above. 
While I am aware that there are many studies that have gone ahead and studied similar topics, 
I believe that a fresh perspective from new eyes could be beneficial to the study. 
Furthermore, I believe that an approach from a Bayesian perspective could 
help us gain additional insight into the topic.

Furthermore, most of these studies have likely been completed to help a company or firm 
determine how much they should offer an employee, 
but I intend to approach this project from the perspective of a prospective employee
who intends to negotiate a starting salary with an employer.

