---
title: "07Chapter - Statistical Rethinking Notes"
output: 
  github_document:
    pandoc_args: --webtex
---

```{r setup}
library(rethinking)
```

```{r}
sppnames <- c( "afarensis", "africanus", "habilis", "boisei", "rudolfensis", "ergaster","sapiens") 
brainvolcc <- c( 438, 452, 612, 521, 752, 871, 1350 ) 
masskg <- c( 37.0 , 35.5 , 34.5 , 41.5 , 55.5 , 61.0 , 53.5 ) 
d <- data.frame( species=sppnames, brain=brainvolcc , mass=masskg )
```


```{r}
d$mass_std <- (d$mass - mean(d$mass))/sd(d$mass)
d$brain_std <- d$brain / max(d$brain)
```
Linear model
```{r}
m7.1 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b * mass_std,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ), data = d
)
```

Quadratic
```{r}
m7.2 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1] * mass_std +b[2] * mass_std ^ 2,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ), data = d, start = list(b = rep(0, 2))
)
```

Cubic

```{r}
m7.3 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1] * mass_std +b[2] * mass_std ^ 2 +
      b[3] * mass_std ^ 3,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1)
  ), data = d, start = list(b = rep(0, 3))
)


```

```{r}
m7.4 <- quap(
  alist(
    brain_std ~ dnorm(mu, exp(log_sigma)),
    mu <- a + b[1] * mass_std +b[2] * mass_std ^ 2 +
      b[3] * mass_std ^ 3 + b[4] * mass_std ^ 4,
    a ~ dnorm(0.5, 1),
    b ~ dnorm(0, 10),
    log_sigma ~ dnorm(0, 1),
  ), data = d, start = list(b = rep(0, 4))
)
```


```{r}
post <- extract.samples(m7.1)
mass_seq <-  seq
```

